-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'SLOT_OPENED';

-- AlterTable
ALTER TABLE "salons" ADD COLUMN     "province" TEXT;

-- CreateTable
CREATE TABLE "favorite_salons" (
    "userId" TEXT NOT NULL,
    "salonId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "favorite_salons_pkey" PRIMARY KEY ("userId","salonId")
);

-- CreateTable
CREATE TABLE "waitlist_entries" (
    "id" TEXT NOT NULL,
    "customerId" TEXT NOT NULL,
    "salonId" TEXT NOT NULL,
    "stylistId" TEXT,
    "dateKey" TEXT NOT NULL,
    "serviceIds" TEXT[],
    "notifiedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "waitlist_entries_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "favorite_salons_salonId_idx" ON "favorite_salons"("salonId");

-- CreateIndex
CREATE INDEX "waitlist_entries_salonId_dateKey_idx" ON "waitlist_entries"("salonId", "dateKey");

-- CreateIndex
CREATE UNIQUE INDEX "waitlist_entries_customerId_salonId_dateKey_key" ON "waitlist_entries"("customerId", "salonId", "dateKey");

-- CreateIndex
CREATE INDEX "salons_province_city_idx" ON "salons"("province", "city");

-- CreateIndex
CREATE INDEX "salons_latitude_longitude_idx" ON "salons"("latitude", "longitude");

-- AddForeignKey
ALTER TABLE "favorite_salons" ADD CONSTRAINT "favorite_salons_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "favorite_salons" ADD CONSTRAINT "favorite_salons_salonId_fkey" FOREIGN KEY ("salonId") REFERENCES "salons"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "waitlist_entries" ADD CONSTRAINT "waitlist_entries_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "waitlist_entries" ADD CONSTRAINT "waitlist_entries_salonId_fkey" FOREIGN KEY ("salonId") REFERENCES "salons"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "waitlist_entries" ADD CONSTRAINT "waitlist_entries_stylistId_fkey" FOREIGN KEY ("stylistId") REFERENCES "stylists"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- Backfill: normalise Arabic ي/ك in existing city names, then fill in the province of every
-- salon whose city is a known county (packages/iran-locations). Others stay NULL until the
-- owner picks a province in settings.
UPDATE "salons" SET "city" = btrim(replace(replace("city", 'ي', 'ی'), 'ك', 'ک'));
UPDATE "salons" SET "province" = CASE "city"
    WHEN 'تبریز' THEN 'آذربایجان شرقی'
    WHEN 'آذرشهر' THEN 'آذربایجان شرقی'
    WHEN 'اسکو' THEN 'آذربایجان شرقی'
    WHEN 'اهر' THEN 'آذربایجان شرقی'
    WHEN 'بستان‌آباد' THEN 'آذربایجان شرقی'
    WHEN 'بناب' THEN 'آذربایجان شرقی'
    WHEN 'جلفا' THEN 'آذربایجان شرقی'
    WHEN 'چاراویماق' THEN 'آذربایجان شرقی'
    WHEN 'خداآفرین' THEN 'آذربایجان شرقی'
    WHEN 'سراب' THEN 'آذربایجان شرقی'
    WHEN 'شبستر' THEN 'آذربایجان شرقی'
    WHEN 'عجب‌شیر' THEN 'آذربایجان شرقی'
    WHEN 'کلیبر' THEN 'آذربایجان شرقی'
    WHEN 'مراغه' THEN 'آذربایجان شرقی'
    WHEN 'مرند' THEN 'آذربایجان شرقی'
    WHEN 'ملکان' THEN 'آذربایجان شرقی'
    WHEN 'میانه' THEN 'آذربایجان شرقی'
    WHEN 'ورزقان' THEN 'آذربایجان شرقی'
    WHEN 'هریس' THEN 'آذربایجان شرقی'
    WHEN 'هشترود' THEN 'آذربایجان شرقی'
    WHEN 'هوراند' THEN 'آذربایجان شرقی'
    WHEN 'ارومیه' THEN 'آذربایجان غربی'
    WHEN 'اشنویه' THEN 'آذربایجان غربی'
    WHEN 'بوکان' THEN 'آذربایجان غربی'
    WHEN 'پلدشت' THEN 'آذربایجان غربی'
    WHEN 'پیرانشهر' THEN 'آذربایجان غربی'
    WHEN 'تکاب' THEN 'آذربایجان غربی'
    WHEN 'چالدران' THEN 'آذربایجان غربی'
    WHEN 'چایپاره' THEN 'آذربایجان غربی'
    WHEN 'خوی' THEN 'آذربایجان غربی'
    WHEN 'سردشت' THEN 'آذربایجان غربی'
    WHEN 'سلماس' THEN 'آذربایجان غربی'
    WHEN 'شاهین‌دژ' THEN 'آذربایجان غربی'
    WHEN 'شوط' THEN 'آذربایجان غربی'
    WHEN 'ماکو' THEN 'آذربایجان غربی'
    WHEN 'مهاباد' THEN 'آذربایجان غربی'
    WHEN 'میاندوآب' THEN 'آذربایجان غربی'
    WHEN 'نقده' THEN 'آذربایجان غربی'
    WHEN 'اردبیل' THEN 'اردبیل'
    WHEN 'اصلاندوز' THEN 'اردبیل'
    WHEN 'بیله‌سوار' THEN 'اردبیل'
    WHEN 'پارس‌آباد' THEN 'اردبیل'
    WHEN 'خلخال' THEN 'اردبیل'
    WHEN 'سرعین' THEN 'اردبیل'
    WHEN 'کوثر' THEN 'اردبیل'
    WHEN 'گرمی' THEN 'اردبیل'
    WHEN 'مشگین‌شهر' THEN 'اردبیل'
    WHEN 'نمین' THEN 'اردبیل'
    WHEN 'نیر' THEN 'اردبیل'
    WHEN 'اصفهان' THEN 'اصفهان'
    WHEN 'آران و بیدگل' THEN 'اصفهان'
    WHEN 'اردستان' THEN 'اصفهان'
    WHEN 'برخوار' THEN 'اصفهان'
    WHEN 'بوئین و میاندشت' THEN 'اصفهان'
    WHEN 'تیران و کرون' THEN 'اصفهان'
    WHEN 'چادگان' THEN 'اصفهان'
    WHEN 'خمینی‌شهر' THEN 'اصفهان'
    WHEN 'خوانسار' THEN 'اصفهان'
    WHEN 'خور و بیابانک' THEN 'اصفهان'
    WHEN 'دهاقان' THEN 'اصفهان'
    WHEN 'سمیرم' THEN 'اصفهان'
    WHEN 'شاهین‌شهر و میمه' THEN 'اصفهان'
    WHEN 'شهرضا' THEN 'اصفهان'
    WHEN 'فریدن' THEN 'اصفهان'
    WHEN 'فریدون‌شهر' THEN 'اصفهان'
    WHEN 'فلاورجان' THEN 'اصفهان'
    WHEN 'کاشان' THEN 'اصفهان'
    WHEN 'کوهپایه' THEN 'اصفهان'
    WHEN 'گلپایگان' THEN 'اصفهان'
    WHEN 'لنجان' THEN 'اصفهان'
    WHEN 'مبارکه' THEN 'اصفهان'
    WHEN 'نائین' THEN 'اصفهان'
    WHEN 'نجف‌آباد' THEN 'اصفهان'
    WHEN 'نطنز' THEN 'اصفهان'
    WHEN 'کرج' THEN 'البرز'
    WHEN 'اشتهارد' THEN 'البرز'
    WHEN 'چهارباغ' THEN 'البرز'
    WHEN 'ساوجبلاغ' THEN 'البرز'
    WHEN 'طالقان' THEN 'البرز'
    WHEN 'فردیس' THEN 'البرز'
    WHEN 'نظرآباد' THEN 'البرز'
    WHEN 'ایلام' THEN 'ایلام'
    WHEN 'آبدانان' THEN 'ایلام'
    WHEN 'ایوان' THEN 'ایلام'
    WHEN 'بدره' THEN 'ایلام'
    WHEN 'چرداول' THEN 'ایلام'
    WHEN 'دره‌شهر' THEN 'ایلام'
    WHEN 'دهلران' THEN 'ایلام'
    WHEN 'سیروان' THEN 'ایلام'
    WHEN 'ملکشاهی' THEN 'ایلام'
    WHEN 'مهران' THEN 'ایلام'
    WHEN 'بوشهر' THEN 'بوشهر'
    WHEN 'تنگستان' THEN 'بوشهر'
    WHEN 'جم' THEN 'بوشهر'
    WHEN 'دشتستان' THEN 'بوشهر'
    WHEN 'دشتی' THEN 'بوشهر'
    WHEN 'دیر' THEN 'بوشهر'
    WHEN 'دیلم' THEN 'بوشهر'
    WHEN 'عسلویه' THEN 'بوشهر'
    WHEN 'کنگان' THEN 'بوشهر'
    WHEN 'گناوه' THEN 'بوشهر'
    WHEN 'تهران' THEN 'تهران'
    WHEN 'اسلامشهر' THEN 'تهران'
    WHEN 'بهارستان' THEN 'تهران'
    WHEN 'پاکدشت' THEN 'تهران'
    WHEN 'پردیس' THEN 'تهران'
    WHEN 'پیشوا' THEN 'تهران'
    WHEN 'دماوند' THEN 'تهران'
    WHEN 'رباط‌کریم' THEN 'تهران'
    WHEN 'ری' THEN 'تهران'
    WHEN 'شمیرانات' THEN 'تهران'
    WHEN 'شهریار' THEN 'تهران'
    WHEN 'فیروزکوه' THEN 'تهران'
    WHEN 'قدس' THEN 'تهران'
    WHEN 'قرچک' THEN 'تهران'
    WHEN 'ملارد' THEN 'تهران'
    WHEN 'ورامین' THEN 'تهران'
    WHEN 'شهرکرد' THEN 'چهارمحال و بختیاری'
    WHEN 'اردل' THEN 'چهارمحال و بختیاری'
    WHEN 'بروجن' THEN 'چهارمحال و بختیاری'
    WHEN 'بن' THEN 'چهارمحال و بختیاری'
    WHEN 'خانمیرزا' THEN 'چهارمحال و بختیاری'
    WHEN 'سامان' THEN 'چهارمحال و بختیاری'
    WHEN 'فارسان' THEN 'چهارمحال و بختیاری'
    WHEN 'کوهرنگ' THEN 'چهارمحال و بختیاری'
    WHEN 'کیار' THEN 'چهارمحال و بختیاری'
    WHEN 'لردگان' THEN 'چهارمحال و بختیاری'
    WHEN 'بیرجند' THEN 'خراسان جنوبی'
    WHEN 'بشرویه' THEN 'خراسان جنوبی'
    WHEN 'خوسف' THEN 'خراسان جنوبی'
    WHEN 'درمیان' THEN 'خراسان جنوبی'
    WHEN 'زیرکوه' THEN 'خراسان جنوبی'
    WHEN 'سرایان' THEN 'خراسان جنوبی'
    WHEN 'سربیشه' THEN 'خراسان جنوبی'
    WHEN 'فردوس' THEN 'خراسان جنوبی'
    WHEN 'قائنات' THEN 'خراسان جنوبی'
    WHEN 'نهبندان' THEN 'خراسان جنوبی'
    WHEN 'مشهد' THEN 'خراسان رضوی'
    WHEN 'باخرز' THEN 'خراسان رضوی'
    WHEN 'بجستان' THEN 'خراسان رضوی'
    WHEN 'بردسکن' THEN 'خراسان رضوی'
    WHEN 'بینالود' THEN 'خراسان رضوی'
    WHEN 'تایباد' THEN 'خراسان رضوی'
    WHEN 'تربت جام' THEN 'خراسان رضوی'
    WHEN 'تربت حیدریه' THEN 'خراسان رضوی'
    WHEN 'جغتای' THEN 'خراسان رضوی'
    WHEN 'جوین' THEN 'خراسان رضوی'
    WHEN 'چناران' THEN 'خراسان رضوی'
    WHEN 'خلیل‌آباد' THEN 'خراسان رضوی'
    WHEN 'خواف' THEN 'خراسان رضوی'
    WHEN 'خوشاب' THEN 'خراسان رضوی'
    WHEN 'داورزن' THEN 'خراسان رضوی'
    WHEN 'درگز' THEN 'خراسان رضوی'
    WHEN 'رشتخوار' THEN 'خراسان رضوی'
    WHEN 'زاوه' THEN 'خراسان رضوی'
    WHEN 'سبزوار' THEN 'خراسان رضوی'
    WHEN 'سرخس' THEN 'خراسان رضوی'
    WHEN 'صالح‌آباد' THEN 'خراسان رضوی'
    WHEN 'فریمان' THEN 'خراسان رضوی'
    WHEN 'فیروزه' THEN 'خراسان رضوی'
    WHEN 'قوچان' THEN 'خراسان رضوی'
    WHEN 'کاشمر' THEN 'خراسان رضوی'
    WHEN 'کلات' THEN 'خراسان رضوی'
    WHEN 'کوهسرخ' THEN 'خراسان رضوی'
    WHEN 'گناباد' THEN 'خراسان رضوی'
    WHEN 'مه‌ولات' THEN 'خراسان رضوی'
    WHEN 'نیشابور' THEN 'خراسان رضوی'
    WHEN 'بجنورد' THEN 'خراسان شمالی'
    WHEN 'اسفراین' THEN 'خراسان شمالی'
    WHEN 'جاجرم' THEN 'خراسان شمالی'
    WHEN 'راز و جرگلان' THEN 'خراسان شمالی'
    WHEN 'شیروان' THEN 'خراسان شمالی'
    WHEN 'فاروج' THEN 'خراسان شمالی'
    WHEN 'گرمه' THEN 'خراسان شمالی'
    WHEN 'مانه' THEN 'خراسان شمالی'
    WHEN 'اهواز' THEN 'خوزستان'
    WHEN 'آبادان' THEN 'خوزستان'
    WHEN 'آغاجاری' THEN 'خوزستان'
    WHEN 'امیدیه' THEN 'خوزستان'
    WHEN 'اندیکا' THEN 'خوزستان'
    WHEN 'اندیمشک' THEN 'خوزستان'
    WHEN 'ایذه' THEN 'خوزستان'
    WHEN 'باغملک' THEN 'خوزستان'
    WHEN 'باوی' THEN 'خوزستان'
    WHEN 'بندر ماهشهر' THEN 'خوزستان'
    WHEN 'بهبهان' THEN 'خوزستان'
    WHEN 'حمیدیه' THEN 'خوزستان'
    WHEN 'خرمشهر' THEN 'خوزستان'
    WHEN 'دزفول' THEN 'خوزستان'
    WHEN 'دشت آزادگان' THEN 'خوزستان'
    WHEN 'رامشیر' THEN 'خوزستان'
    WHEN 'رامهرمز' THEN 'خوزستان'
    WHEN 'شادگان' THEN 'خوزستان'
    WHEN 'شوش' THEN 'خوزستان'
    WHEN 'شوشتر' THEN 'خوزستان'
    WHEN 'کارون' THEN 'خوزستان'
    WHEN 'گتوند' THEN 'خوزستان'
    WHEN 'لالی' THEN 'خوزستان'
    WHEN 'مسجدسلیمان' THEN 'خوزستان'
    WHEN 'هفتکل' THEN 'خوزستان'
    WHEN 'هندیجان' THEN 'خوزستان'
    WHEN 'هویزه' THEN 'خوزستان'
    WHEN 'زنجان' THEN 'زنجان'
    WHEN 'ابهر' THEN 'زنجان'
    WHEN 'ایجرود' THEN 'زنجان'
    WHEN 'خدابنده' THEN 'زنجان'
    WHEN 'خرمدره' THEN 'زنجان'
    WHEN 'سلطانیه' THEN 'زنجان'
    WHEN 'طارم' THEN 'زنجان'
    WHEN 'ماهنشان' THEN 'زنجان'
    WHEN 'سمنان' THEN 'سمنان'
    WHEN 'آرادان' THEN 'سمنان'
    WHEN 'دامغان' THEN 'سمنان'
    WHEN 'سرخه' THEN 'سمنان'
    WHEN 'شاهرود' THEN 'سمنان'
    WHEN 'گرمسار' THEN 'سمنان'
    WHEN 'مهدی‌شهر' THEN 'سمنان'
    WHEN 'میامی' THEN 'سمنان'
    WHEN 'زاهدان' THEN 'سیستان و بلوچستان'
    WHEN 'ایرانشهر' THEN 'سیستان و بلوچستان'
    WHEN 'بمپور' THEN 'سیستان و بلوچستان'
    WHEN 'تفتان' THEN 'سیستان و بلوچستان'
    WHEN 'چابهار' THEN 'سیستان و بلوچستان'
    WHEN 'خاش' THEN 'سیستان و بلوچستان'
    WHEN 'دشتیاری' THEN 'سیستان و بلوچستان'
    WHEN 'دلگان' THEN 'سیستان و بلوچستان'
    WHEN 'راسک' THEN 'سیستان و بلوچستان'
    WHEN 'زابل' THEN 'سیستان و بلوچستان'
    WHEN 'زهک' THEN 'سیستان و بلوچستان'
    WHEN 'سراوان' THEN 'سیستان و بلوچستان'
    WHEN 'سرباز' THEN 'سیستان و بلوچستان'
    WHEN 'سیب و سوران' THEN 'سیستان و بلوچستان'
    WHEN 'فنوج' THEN 'سیستان و بلوچستان'
    WHEN 'قصرقند' THEN 'سیستان و بلوچستان'
    WHEN 'کنارک' THEN 'سیستان و بلوچستان'
    WHEN 'مهرستان' THEN 'سیستان و بلوچستان'
    WHEN 'میرجاوه' THEN 'سیستان و بلوچستان'
    WHEN 'نیکشهر' THEN 'سیستان و بلوچستان'
    WHEN 'نیمروز' THEN 'سیستان و بلوچستان'
    WHEN 'هامون' THEN 'سیستان و بلوچستان'
    WHEN 'هیرمند' THEN 'سیستان و بلوچستان'
    WHEN 'شیراز' THEN 'فارس'
    WHEN 'آباده' THEN 'فارس'
    WHEN 'ارسنجان' THEN 'فارس'
    WHEN 'استهبان' THEN 'فارس'
    WHEN 'اقلید' THEN 'فارس'
    WHEN 'اوز' THEN 'فارس'
    WHEN 'بختگان' THEN 'فارس'
    WHEN 'بوانات' THEN 'فارس'
    WHEN 'بیضا' THEN 'فارس'
    WHEN 'پاسارگاد' THEN 'فارس'
    WHEN 'جهرم' THEN 'فارس'
    WHEN 'خرامه' THEN 'فارس'
    WHEN 'خرم‌بید' THEN 'فارس'
    WHEN 'خنج' THEN 'فارس'
    WHEN 'داراب' THEN 'فارس'
    WHEN 'رستم' THEN 'فارس'
    WHEN 'زرقان' THEN 'فارس'
    WHEN 'زرین‌دشت' THEN 'فارس'
    WHEN 'سپیدان' THEN 'فارس'
    WHEN 'سرچهان' THEN 'فارس'
    WHEN 'سروستان' THEN 'فارس'
    WHEN 'فراشبند' THEN 'فارس'
    WHEN 'فسا' THEN 'فارس'
    WHEN 'فیروزآباد' THEN 'فارس'
    WHEN 'قیر و کارزین' THEN 'فارس'
    WHEN 'کازرون' THEN 'فارس'
    WHEN 'کوار' THEN 'فارس'
    WHEN 'کوه‌چنار' THEN 'فارس'
    WHEN 'گراش' THEN 'فارس'
    WHEN 'لارستان' THEN 'فارس'
    WHEN 'لامرد' THEN 'فارس'
    WHEN 'مرودشت' THEN 'فارس'
    WHEN 'ممسنی' THEN 'فارس'
    WHEN 'مهر' THEN 'فارس'
    WHEN 'نی‌ریز' THEN 'فارس'
    WHEN 'قزوین' THEN 'قزوین'
    WHEN 'آبیک' THEN 'قزوین'
    WHEN 'البرز' THEN 'قزوین'
    WHEN 'آوج' THEN 'قزوین'
    WHEN 'بوئین‌زهرا' THEN 'قزوین'
    WHEN 'تاکستان' THEN 'قزوین'
    WHEN 'قم' THEN 'قم'
    WHEN 'سنندج' THEN 'کردستان'
    WHEN 'بانه' THEN 'کردستان'
    WHEN 'بیجار' THEN 'کردستان'
    WHEN 'دهگلان' THEN 'کردستان'
    WHEN 'دیواندره' THEN 'کردستان'
    WHEN 'سروآباد' THEN 'کردستان'
    WHEN 'سقز' THEN 'کردستان'
    WHEN 'قروه' THEN 'کردستان'
    WHEN 'کامیاران' THEN 'کردستان'
    WHEN 'مریوان' THEN 'کردستان'
    WHEN 'کرمان' THEN 'کرمان'
    WHEN 'ارزوئیه' THEN 'کرمان'
    WHEN 'انار' THEN 'کرمان'
    WHEN 'بافت' THEN 'کرمان'
    WHEN 'بردسیر' THEN 'کرمان'
    WHEN 'بم' THEN 'کرمان'
    WHEN 'جیرفت' THEN 'کرمان'
    WHEN 'رابر' THEN 'کرمان'
    WHEN 'راور' THEN 'کرمان'
    WHEN 'رفسنجان' THEN 'کرمان'
    WHEN 'رودبار جنوب' THEN 'کرمان'
    WHEN 'ریگان' THEN 'کرمان'
    WHEN 'زرند' THEN 'کرمان'
    WHEN 'سیرجان' THEN 'کرمان'
    WHEN 'شهربابک' THEN 'کرمان'
    WHEN 'عنبرآباد' THEN 'کرمان'
    WHEN 'فاریاب' THEN 'کرمان'
    WHEN 'فهرج' THEN 'کرمان'
    WHEN 'قلعه‌گنج' THEN 'کرمان'
    WHEN 'کوهبنان' THEN 'کرمان'
    WHEN 'کهنوج' THEN 'کرمان'
    WHEN 'منوجان' THEN 'کرمان'
    WHEN 'نرماشیر' THEN 'کرمان'
    WHEN 'کرمانشاه' THEN 'کرمانشاه'
    WHEN 'اسلام‌آباد غرب' THEN 'کرمانشاه'
    WHEN 'پاوه' THEN 'کرمانشاه'
    WHEN 'ثلاث باباجانی' THEN 'کرمانشاه'
    WHEN 'جوانرود' THEN 'کرمانشاه'
    WHEN 'دالاهو' THEN 'کرمانشاه'
    WHEN 'روانسر' THEN 'کرمانشاه'
    WHEN 'سرپل ذهاب' THEN 'کرمانشاه'
    WHEN 'سنقر' THEN 'کرمانشاه'
    WHEN 'صحنه' THEN 'کرمانشاه'
    WHEN 'قصر شیرین' THEN 'کرمانشاه'
    WHEN 'کنگاور' THEN 'کرمانشاه'
    WHEN 'گیلانغرب' THEN 'کرمانشاه'
    WHEN 'هرسین' THEN 'کرمانشاه'
    WHEN 'بویراحمد' THEN 'کهگیلویه و بویراحمد'
    WHEN 'باشت' THEN 'کهگیلویه و بویراحمد'
    WHEN 'بهمئی' THEN 'کهگیلویه و بویراحمد'
    WHEN 'چرام' THEN 'کهگیلویه و بویراحمد'
    WHEN 'دنا' THEN 'کهگیلویه و بویراحمد'
    WHEN 'کهگیلویه' THEN 'کهگیلویه و بویراحمد'
    WHEN 'گچساران' THEN 'کهگیلویه و بویراحمد'
    WHEN 'لنده' THEN 'کهگیلویه و بویراحمد'
    WHEN 'مارگون' THEN 'کهگیلویه و بویراحمد'
    WHEN 'گرگان' THEN 'گلستان'
    WHEN 'آزادشهر' THEN 'گلستان'
    WHEN 'آق‌قلا' THEN 'گلستان'
    WHEN 'بندر ترکمن' THEN 'گلستان'
    WHEN 'بندر گز' THEN 'گلستان'
    WHEN 'رامیان' THEN 'گلستان'
    WHEN 'علی‌آباد کتول' THEN 'گلستان'
    WHEN 'کردکوی' THEN 'گلستان'
    WHEN 'کلاله' THEN 'گلستان'
    WHEN 'گالیکش' THEN 'گلستان'
    WHEN 'گمیشان' THEN 'گلستان'
    WHEN 'گنبد کاووس' THEN 'گلستان'
    WHEN 'مراوه‌تپه' THEN 'گلستان'
    WHEN 'مینودشت' THEN 'گلستان'
    WHEN 'رشت' THEN 'گیلان'
    WHEN 'آستارا' THEN 'گیلان'
    WHEN 'آستانه اشرفیه' THEN 'گیلان'
    WHEN 'املش' THEN 'گیلان'
    WHEN 'بندر انزلی' THEN 'گیلان'
    WHEN 'تالش' THEN 'گیلان'
    WHEN 'رضوانشهر' THEN 'گیلان'
    WHEN 'رودبار' THEN 'گیلان'
    WHEN 'رودسر' THEN 'گیلان'
    WHEN 'سیاهکل' THEN 'گیلان'
    WHEN 'شفت' THEN 'گیلان'
    WHEN 'صومعه‌سرا' THEN 'گیلان'
    WHEN 'فومن' THEN 'گیلان'
    WHEN 'لاهیجان' THEN 'گیلان'
    WHEN 'لنگرود' THEN 'گیلان'
    WHEN 'ماسال' THEN 'گیلان'
    WHEN 'خرم‌آباد' THEN 'لرستان'
    WHEN 'ازنا' THEN 'لرستان'
    WHEN 'الیگودرز' THEN 'لرستان'
    WHEN 'بروجرد' THEN 'لرستان'
    WHEN 'پلدختر' THEN 'لرستان'
    WHEN 'چگنی' THEN 'لرستان'
    WHEN 'دلفان' THEN 'لرستان'
    WHEN 'دورود' THEN 'لرستان'
    WHEN 'رومشکان' THEN 'لرستان'
    WHEN 'سلسله' THEN 'لرستان'
    WHEN 'کوهدشت' THEN 'لرستان'
    WHEN 'ساری' THEN 'مازندران'
    WHEN 'آمل' THEN 'مازندران'
    WHEN 'بابل' THEN 'مازندران'
    WHEN 'بابلسر' THEN 'مازندران'
    WHEN 'بهشهر' THEN 'مازندران'
    WHEN 'تنکابن' THEN 'مازندران'
    WHEN 'جویبار' THEN 'مازندران'
    WHEN 'چالوس' THEN 'مازندران'
    WHEN 'رامسر' THEN 'مازندران'
    WHEN 'سوادکوه' THEN 'مازندران'
    WHEN 'سوادکوه شمالی' THEN 'مازندران'
    WHEN 'سیمرغ' THEN 'مازندران'
    WHEN 'عباس‌آباد' THEN 'مازندران'
    WHEN 'فریدونکنار' THEN 'مازندران'
    WHEN 'قائم‌شهر' THEN 'مازندران'
    WHEN 'کلاردشت' THEN 'مازندران'
    WHEN 'گلوگاه' THEN 'مازندران'
    WHEN 'محمودآباد' THEN 'مازندران'
    WHEN 'میاندورود' THEN 'مازندران'
    WHEN 'نکا' THEN 'مازندران'
    WHEN 'نور' THEN 'مازندران'
    WHEN 'نوشهر' THEN 'مازندران'
    WHEN 'اراک' THEN 'مرکزی'
    WHEN 'آشتیان' THEN 'مرکزی'
    WHEN 'تفرش' THEN 'مرکزی'
    WHEN 'خمین' THEN 'مرکزی'
    WHEN 'خنداب' THEN 'مرکزی'
    WHEN 'دلیجان' THEN 'مرکزی'
    WHEN 'زرندیه' THEN 'مرکزی'
    WHEN 'ساوه' THEN 'مرکزی'
    WHEN 'شازند' THEN 'مرکزی'
    WHEN 'فراهان' THEN 'مرکزی'
    WHEN 'کمیجان' THEN 'مرکزی'
    WHEN 'محلات' THEN 'مرکزی'
    WHEN 'بندرعباس' THEN 'هرمزگان'
    WHEN 'ابوموسی' THEN 'هرمزگان'
    WHEN 'بستک' THEN 'هرمزگان'
    WHEN 'بشاگرد' THEN 'هرمزگان'
    WHEN 'بندر خمیر' THEN 'هرمزگان'
    WHEN 'بندر لنگه' THEN 'هرمزگان'
    WHEN 'پارسیان' THEN 'هرمزگان'
    WHEN 'جاسک' THEN 'هرمزگان'
    WHEN 'حاجی‌آباد' THEN 'هرمزگان'
    WHEN 'رودان' THEN 'هرمزگان'
    WHEN 'سیریک' THEN 'هرمزگان'
    WHEN 'قشم' THEN 'هرمزگان'
    WHEN 'میناب' THEN 'هرمزگان'
    WHEN 'همدان' THEN 'همدان'
    WHEN 'اسدآباد' THEN 'همدان'
    WHEN 'بهار' THEN 'همدان'
    WHEN 'تویسرکان' THEN 'همدان'
    WHEN 'رزن' THEN 'همدان'
    WHEN 'فامنین' THEN 'همدان'
    WHEN 'کبودرآهنگ' THEN 'همدان'
    WHEN 'ملایر' THEN 'همدان'
    WHEN 'نهاوند' THEN 'همدان'
    WHEN 'یزد' THEN 'یزد'
    WHEN 'ابرکوه' THEN 'یزد'
    WHEN 'اردکان' THEN 'یزد'
    WHEN 'اشکذر' THEN 'یزد'
    WHEN 'بافق' THEN 'یزد'
    WHEN 'بهاباد' THEN 'یزد'
    WHEN 'تفت' THEN 'یزد'
    WHEN 'خاتم' THEN 'یزد'
    WHEN 'طبس' THEN 'یزد'
    WHEN 'مهریز' THEN 'یزد'
    WHEN 'میبد' THEN 'یزد'
    ELSE NULL
  END;

-- A pin is both coordinates or neither.
UPDATE "salons" SET "latitude" = NULL, "longitude" = NULL WHERE ("latitude" IS NULL) <> ("longitude" IS NULL);
ALTER TABLE "salons" ADD CONSTRAINT "salons_coordinates_pair" CHECK (("latitude" IS NULL) = ("longitude" IS NULL));
